language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install --use-mirrors coveralls"
script: coverage run --source=xs_authserver test_xs_authserver.py
after_success:
    coveralls
